name: Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: DockerHub Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ghcr Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/nginx-docker
            ghcr.io/${{ github.actor }}/nginx-docker

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}